name: Setup Rust (cache & toolchain)
runs:
  using: composite
  steps:
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - uses: Swatinem/rust-cache@v2
